/**
 * `AnimeGenreSearch` / `AnimeStudios` enums ported 1:1 from
 * MALClient.Models/Enums/AnimeGenreSearch.cs and AnimeStudiosEnum.cs.
 *
 * The original builds both grids with
 * `Enum.GetValues(...).OrderBy(val => val.ToString())` and renders
 * `GetDescription()` (the [Description] text, falling back to the member name),
 * so entries are sorted by the C# member name while the label is the
 * description.
 */

export interface GridChoice {
  /** MAL genre id / producer (studio) id. */
  id: number;
  /** Label rendered in the cell (`GetDescription()`). */
  label: string;
}

/** Sorted by enum member name — matches `OrderBy(ToString())`. */
export const GENRE_CHOICES: GridChoice[] = [
  { id: 1, label: "Action" },
  { id: 2, label: "Adventure" },
  { id: 5, label: "AvanteGarde" },
  { id: 46, label: "AwardWinning" },
  { id: 28, label: "BoysLove" },
  { id: 3, label: "Cars" },
  { id: 4, label: "Comedy" },
  { id: 6, label: "Demons" },
  { id: 8, label: "Drama" },
  { id: 9, label: "Ecchi" },
  { id: 49, label: "Erotica" },
  { id: 10, label: "Fantasy" },
  { id: 11, label: "Game" },
  { id: 26, label: "GirlsLove" },
  { id: 47, label: "Gourmet" },
  { id: 35, label: "Harem" },
  { id: 12, label: "Hentai" },
  { id: 13, label: "Historical" },
  { id: 14, label: "Horror" },
  { id: 43, label: "Josei" },
  { id: 15, label: "Kids" },
  { id: 16, label: "Magic" },
  { id: 17, label: "MartialArts" },
  { id: 18, label: "Mecha" },
  { id: 38, label: "Military" },
  { id: 19, label: "Music" },
  { id: 7, label: "Mystery" },
  { id: 20, label: "Parody" },
  { id: 39, label: "Police" },
  { id: 40, label: "Psychological" },
  { id: 22, label: "Romance" },
  { id: 21, label: "Samurai" },
  { id: 23, label: "School" },
  { id: 24, label: "SciFi" },
  { id: 42, label: "Seinen" },
  { id: 25, label: "Shoujo" },
  { id: 27, label: "Shounen" },
  { id: 36, label: "SliceOfLife" },
  { id: 29, label: "Space" },
  { id: 30, label: "Sports" },
  { id: 37, label: "Supernatural" },
  { id: 31, label: "SuperPower" },
  { id: 41, label: "Suspense" },
  { id: 32, label: "Vampire" },
  { id: 48, label: "WorkLife" },
];

/** `AnimeStudios` — sorted by member name, labels are the descriptions. */
export const STUDIO_CHOICES: GridChoice[] = [
  { id: 1500, label: "ABC Animation" },
  { id: 667, label: "AC Create" },
  { id: 179, label: "A.C.G.T." },
  { id: 60, label: "Actas" },
  { id: 121, label: "Active" },
  { id: 410, label: "Adult Source Media" },
  { id: 97, label: "ADV Films" },
  { id: 1225, label: "Age Global Networks" },
  { id: 183, label: "Agent 21" },
  { id: 1041, label: "Ai Addiction" },
  { id: 48, label: "AIC" },
  { id: 88, label: "AIC A.S.T.A." },
  { id: 436, label: "AIC Build" },
  { id: 292, label: "AIC Plus+" },
  { id: 83, label: "AIC Spirits" },
  { id: 30, label: "Ajia-Do" },
  { id: 1373, label: "Akita Shoten" },
  { id: 171, label: "A-Line" },
  { id: 779, label: "AMG MUSIC" },
  { id: 1313, label: "Amuse" },
  { id: 124, label: "Animac" },
  { id: 1243, label: "AniMan" },
  { id: 386, label: "Animaruya" },
  { id: 155, label: "animate Film" },
  { id: 1449, label: "Animatic" },
  { id: 929, label: "Animation Do" },
  { id: 140, label: "Animax" },
  { id: 1463, label: "Anime Antenna Iinkai" },
  { id: 1723, label: "Anime Beans" },
  { id: 1510, label: "Anime Consortium Japan" },
  { id: 310, label: "AnimEigo" },
  { id: 17, label: "Aniplex" },
  { id: 493, label: "Aniplex of America" },
  { id: 56, label: "A-1 Pictures" },
  { id: 77, label: "APPP" },
  { id: 38, label: "Arms" },
  { id: 8, label: "Artland" },
  { id: 72, label: "Artmic" },
  { id: 1415, label: "Asahi Broadcasting" },
  { id: 406, label: "Asahi Production" },
  { id: 1318, label: "Asahi Shimbun" },
  { id: 142, label: "Asatsu DK" },
  { id: 473, label: "Ascension" },
  { id: 681, label: "ASCII Media Works" },
  { id: 242, label: "Ashi Production" },
  { id: 1635, label: "A-Sketch" },
  { id: 517, label: "Asmik Ace" },
  { id: 163, label: "Asread" },
  { id: 579, label: "AT-2" },
  { id: 1175, label: "Atelier Musa" },
  { id: 344, label: "Atlus" },
  { id: 238, label: "AT-X" },
  { id: 1009, label: "Aubec" },
  { id: 1461, label: "Audio Tanaka" },
  { id: 52, label: "Avex Entertainment" },
  { id: 1284, label: "Avex Pictures" },
  { id: 1299, label: "AXsiZ" },
  { id: 230, label: "Bandai" },
  { id: 1588, label: "Bandai Channel" },
  { id: 233, label: "Bandai Entertainment" },
  { id: 1840, label: "Bandai Namco Arts" },
  { id: 1233, label: "Bandai Namco Entertainment" },
  { id: 1097, label: "Bandai Namco Games" },
  { id: 687, label: "Bandai Namco Live Creative" },
  { id: 1258, label: "Bandai Namco Pictures" },
  { id: 23, label: "Bandai Visual" },
  { id: 1466, label: "Bandai Visual USA" },
  { id: 1121, label: "Banpresto" },
  { id: 271, label: "Barnum Studio" },
  { id: 1139, label: "BEAM Entertainment" },
  { id: 322, label: "Bee Media" },
  { id: 5, label: "Bee Train" },
  { id: 1706, label: "Beijing Rocen Digital" },
  { id: 1043, label: "Benesse Corporation" },
  { id: 89, label: "BeSTACK" },
  { id: 1584, label: "Beyond C." },
  { id: 1157, label: "Big Bang" },
  { id: 789, label: "BIGLOBE" },
  { id: 351, label: "Big West" },
  { id: 1414, label: "bilibili" },
  { id: 441, label: "8bit" },
  { id: 1385, label: "Blue Cat" },
  { id: 4, label: "Bones" },
  { id: 981, label: "BOOTLEG" },
  { id: 1487, label: "Bouncy" },
  { id: 112, label: "Brain's Base" },
  { id: 1093, label: "BreakBottle" },
  { id: 397, label: "Bridge" },
  { id: 116, label: "Broccoli" },
  { id: 1416, label: "BS11" },
  { id: 843, label: "BS Fuji" },
  { id: 693, label: "BS-TBS" },
  { id: 775, label: "Bushiroad" },
  { id: 605, label: "C2C" },
  { id: 240, label: "Capcom" },
  { id: 146, label: "CBC" },
  { id: 1480, label: "CBS" },
  { id: 284, label: "Central Park Media" },
  { id: 462, label: "Chaos Project" },
  { id: 665, label: "chara-ani.com" },
  { id: 402, label: "ChiChinoya" },
  { id: 1728, label: "China Literature Limited" },
  { id: 1546, label: "Chippai" },
  { id: 1288, label: "Chrono Gear Creative" },
  { id: 1835, label: "CloverWorks" },
  { id: 1460, label: "Coastline Animation Studio" },
  { id: 519, label: "Collaboration Works" },
  { id: 1831, label: "Colored-Pencil Animation Design" },
  { id: 1481, label: "comico" },
  { id: 291, label: "CoMix Wave Films" },
  { id: 957, label: "Connect" },
  { id: 1554, label: "Contents Seed" },
  { id: 745, label: "Cosmic Ray" },
  { id: 619, label: "Cospa" },
  { id: 821, label: "Cotton Doll" },
  { id: 1357, label: "Craftar Studios" },
  { id: 1195, label: "Creators in Pack" },
  { id: 1961, label: "Creatures Inc." },
  { id: 296, label: "Critical Mass Video" },
  { id: 1468, label: "Crunchyroll" },
  { id: 1784, label: "Crunchyroll SC Anime Fund" },
  { id: 1075, label: "C-Station" },
  { id: 231, label: "CyberConnect2" },
  { id: 1099, label: "Cyclone Graphics" },
  { id: 1587, label: "Cygames" },
  { id: 244, label: "D3" },
  { id: 228, label: "Daewon Media" },
  { id: 278, label: "Daiei" },
  { id: 1215, label: "Daiichikosho" },
  { id: 1111, label: "DandeLion Animation Studio" },
  { id: 39, label: "Daume" },
  { id: 287, label: "David Production" },
  { id: 315, label: "DAX Production" },
  { id: 711, label: "Delfi Sound" },
  { id: 1576, label: "DeNA" },
  { id: 53, label: "Dentsu" },
  { id: 1607, label: "Dentsu Tec" },
  { id: 486, label: "Digital Frontier" },
  { id: 206, label: "Digital Works" },
  { id: 51, label: "Diomedea" },
  { id: 324, label: "Directions" },
  { id: 467, label: "Discotek Media" },
  { id: 294, label: "Discovery" },
  { id: 1039, label: "DIVE II Entertainment" },
  { id: 276, label: "DLE" },
  { id: 1542, label: "DMM.com" },
  { id: 1673, label: "DMM.futureworks" },
  { id: 1671, label: "DMM pictures" },
  { id: 1334, label: "Docomo Anime Store" },
  { id: 95, label: "Doga Kobo" },
  { id: 1025, label: "Dongwoo A&E" },
  { id: 615, label: "Dream Creation" },
  { id: 399, label: "Dream Force" },
  { id: 164, label: "d-rights" },
  { id: 715, label: "Dwango" },
  { id: 1133, label: "dwarf" },
  { id: 921, label: "Dynamic Planning" },
  { id: 925, label: "Earth Star Entertainment" },
  { id: 1501, label: "East Japan Marketing & Communications" },
  { id: 1522, label: "Echoes" },
  { id: 1351, label: "EDGE" },
  { id: 154, label: "E&G Films" },
  { id: 1444, label: "Egg Firm" },
  { id: 191, label: "Eiken" },
  { id: 815, label: "EMI" },
  { id: 1530, label: "Emon" },
  { id: 1264, label: "EMT²" },
  { id: 354, label: "Encourage Films" },
  { id: 311, label: "Enoki Films" },
  { id: 392, label: "Enterbrain" },
  { id: 1598, label: "Exa International" },
  { id: 1594, label: "Exit Tunes" },
  { id: 866, label: "Fanworks" },
  { id: 91, label: "feel." },
  { id: 1358, label: "Fields" },
  { id: 426, label: "Filmlink International" },
  { id: 267, label: "Five Ways" },
  { id: 1163, label: "Flatiron Film Company" },
  { id: 1531, label: "Flavors Soft" },
  { id: 464, label: "flying DOG" },
  { id: 285, label: "Four Some" },
  { id: 61, label: "Frontier Works" },
  { id: 69, label: "Front Line" },
  { id: 1556, label: "Fuji Creative" },
  { id: 1664, label: "Fujimi Shobo" },
  { id: 769, label: "Fuji Pacific Music Publishing" },
  { id: 169, label: "Fuji TV" },
  { id: 102, label: "Funimation" },
  { id: 1590, label: "Furyu" },
  { id: 1377, label: "Futabasha" },
  { id: 470, label: "GAGA" },
  { id: 1314, label: "Gaina" },
  { id: 6, label: "Gainax" },
  { id: 198, label: "Gakken" },
  { id: 1091, label: "Gakken Eigakyoku" },
  { id: 721, label: "GANSIS" },
  { id: 400, label: "Gathering" },
  { id: 1286, label: "10Gauge" },
  { id: 1350, label: "G.CMay Animation & Film" },
  { id: 42, label: "GDH" },
  { id: 79, label: "Genco" },
  { id: 1459, label: "Geneon Entertainment USA" },
  { id: 31, label: "Geneon Universal Entertainment" },
  { id: 1393, label: "Geno Studio" },
  { id: 131, label: "G&G Entertainment" },
  { id: 880, label: "gimik" },
  { id: 783, label: "GKIDS" },
  { id: 1369, label: "G-Lam" },
  { id: 1255, label: "Glovision" },
  { id: 309, label: "GoHands" },
  { id: 3, label: "Gonzo" },
  { id: 1261, label: "Good Smile Company" },
  { id: 894, label: "Graphinica" },
  { id: 1815, label: "Gree" },
  { id: 152, label: "Green Bunny" },
  { id: 1254, label: "Grooove" },
  { id: 391, label: "Grouper Productions" },
  { id: 86, label: "Group TAC" },
  { id: 1602, label: "GYAO!" },
  { id: 1488, label: "Hakuhodo DY Media Partners" },
  { id: 1333, label: "Hakuhodo DY Music & Pictures" },
  { id: 148, label: "Hakusensha" },
  { id: 213, label: "Half H.P Studio" },
  { id: 34, label: "Hal Film Maker" },
  { id: 1325, label: "Haoliners Animation League" },
  { id: 787, label: "Happinet Pictures" },
  { id: 465, label: "Hasbro" },
  { id: 367, label: "Heewon Entertainment" },
  { id: 138, label: "Himajin Planning" },
  { id: 1716, label: "Hipland Music Corporation" },
  { id: 1702, label: "Hiroshima Television" },
  { id: 547, label: "Hobby Japan" },
  { id: 1360, label: "Hoods Drifters Studio" },
  { id: 346, label: "Hoods Entertainment" },
  { id: 134, label: "HoriPro" },
  { id: 797, label: "Houbunsha" },
  { id: 1331, label: "i0+" },
  { id: 1582, label: "Ichijinsha" },
  { id: 193, label: "Idea Factory" },
  { id: 1169, label: "ILCA" },
  { id: 170, label: "Imagica" },
  { id: 75, label: "Imagin" },
  { id: 870, label: "Index" },
  { id: 1386, label: "Infinite" },
  { id: 1806, label: "iQIYI" },
  { id: 1235, label: "I was a Ballerina" },
  { id: 1605, label: "I Will" },
  { id: 573, label: "JapanAnime" },
  { id: 342, label: "Japan Home Video" },
  { id: 7, label: "J.C.Staff" },
  { id: 1517, label: "Jinnan Studio" },
  { id: 444, label: "Jinnis Animation Studios" },
  { id: 755, label: "Jumondo" },
  { id: 1645, label: "Just Production" },
  { id: 432, label: "Kachidoki Studio" },
  { id: 1696, label: "Kadokawa" },
  { id: 685, label: "Kadokawa Contents Gate" },
  { id: 1551, label: "Kadokawa Media House" },
  { id: 352, label: "Kadokawa Pictures Japan" },
  { id: 262, label: "Kadokawa Pictures USA" },
  { id: 113, label: "Kadokawa Shoten" },
  { id: 259, label: "Kaeruotoko Shokai" },
  { id: 437, label: "Kamikaze Douga" },
  { id: 1592, label: "Kamio Japan" },
  { id: 330, label: "Kanaban Graphics" },
  { id: 288, label: "Kaname Productions" },
  { id: 1677, label: "Kanetsu Co., LTD." },
  { id: 1494, label: "Kanon Sound" },
  { id: 1412, label: "Kansai Telecasting" },
  { id: 1947, label: "Kate Arrow" },
  { id: 411, label: "KBS" },
  { id: 283, label: "KENMedia" },
  { id: 47, label: "Khara" },
  { id: 252, label: "4Kids Entertainment" },
  { id: 158, label: "Kids Station" },
  { id: 290, label: "Kinema Citrus" },
  { id: 1344, label: "King Records" },
  { id: 1653, label: "Kinoshita Group Holdings" },
  { id: 1679, label: "Kinyosha" },
  { id: 99, label: "Kitty Films" },
  { id: 321, label: "Kitty Media" },
  { id: 460, label: "KlockWorx" },
  { id: 452, label: "Knack Productions" },
  { id: 159, label: "Kodansha" },
  { id: 241, label: "Koei" },
  { id: 281, label: "Kokusai Eigasha" },
  { id: 85, label: "Konami" },
  { id: 1291, label: "KOO-KI" },
  { id: 50, label: "KSS" },
  { id: 377, label: "Kuri Jikken Manga Kobo" },
  { id: 1411, label: "Kyoraku Industrial Holdings" },
  { id: 2, label: "Kyoto Animation" },
  { id: 833, label: "Kyotoma" },
  { id: 563, label: "LandQ studios" },
  { id: 104, label: "Lantis" },
  { id: 1408, label: "Lastrum Music" },
  { id: 1496, label: "Lawson" },
  { id: 1309, label: "Lawson HMV Entertainment" },
  { id: 1087, label: "Lay-duce" },
  { id: 414, label: "Lemon Heart" },
  { id: 456, label: "Lerche" },
  { id: 1829, label: "Lesprit" },
  { id: 1428, label: "Level-5" },
  { id: 1936, label: "Liberty Animation Studio" },
  { id: 839, label: "LIDENFILMS" },
  { id: 1268, label: "L²Studio" },
  { id: 1123, label: "Lucent Pictures Entertainment" },
  { id: 11, label: "Madhouse" },
  { id: 963, label: "MAGES." },
  { id: 1452, label: "Mag Garden" },
  { id: 207, label: "Magic Bus" },
  { id: 306, label: "Magic Capsule" },
  { id: 490, label: "Maiden Japan" },
  { id: 143, label: "Mainichi Broadcasting System" },
  { id: 947, label: "Manga Entertainment" },
  { id: 32, label: "Manglobe" },
  { id: 569, label: "MAPPA" },
  { id: 1363, label: "Marine Entertainment" },
  { id: 165, label: "Marubeni" },
  { id: 483, label: "Marvel Entertainment" },
  { id: 82, label: "Marvelous" },
  { id: 751, label: "Marvelous AQL" },
  { id: 424, label: "Mary Jane" },
  { id: 1296, label: "Marza Animation Planet" },
  { id: 1424, label: "Media Bank" },
  { id: 250, label: "Media Blasters" },
  { id: 108, label: "Media Factory" },
  { id: 135, label: "MediaNet" },
  { id: 1337, label: "Medicos Entertainment" },
  { id: 71, label: "Mellow Head" },
  { id: 647, label: "Memory-Tech" },
  { id: 1754, label: "Meruhensha" },
  { id: 25, label: "Milky Animation Label" },
  { id: 398, label: "Milky Cartoon" },
  { id: 1237, label: "Millepensee" },
  { id: 1725, label: "Minakata Laboratory" },
  { id: 1249, label: "Mirai Film" },
  { id: 501, label: "Miramax Films" },
  { id: 1077, label: "MMDGP" },
  { id: 1213, label: "Mobcast" },
  { id: 40, label: "m.o.e." },
  { id: 166, label: "Movic" },
  { id: 463, label: "M.S.C" },
  { id: 319, label: "MS Pictures" },
  { id: 68, label: "Mushi Production" },
  { id: 1744, label: "My Theater D.D." },
  { id: 1366, label: "Nagoya Broadcasting Network" },
  { id: 951, label: "NAZ" },
  { id: 1113, label: "NBCUniversal Entertainment Japan" },
  { id: 215, label: "Nelvana" },
  { id: 819, label: "Next Media Animation" },
  { id: 852, label: "Nexus" },
  { id: 111, label: "NHK" },
  { id: 1797, label: "NHK Enterprises" },
  { id: 1589, label: "NichiNare" },
  { id: 1585, label: "Nichion" },
  { id: 139, label: "Nihon Ad Systems" },
  { id: 513, label: "Nikkatsu" },
  { id: 503, label: "Nintendo" },
  { id: 22, label: "Nippon Animation" },
  { id: 323, label: "Nippon Columbia" },
  { id: 1418, label: "Nippon Television Music" },
  { id: 1003, label: "Nippon Television Network" },
  { id: 372, label: "NIS America, Inc." },
  { id: 459, label: "Nitroplus" },
  { id: 70, label: "Nomad" },
  { id: 1534, label: "North Stars Pictures" },
  { id: 703, label: "Notes" },
  { id: 217, label: "Nozomi Entertainment" },
  { id: 689, label: "NTT Docomo" },
  { id: 1614, label: "NTT Plala" },
  { id: 270, label: "NuTech Digital" },
  { id: 595, label: "NYAV Post" },
  { id: 67, label: "OB Planning" },
  { id: 571, label: "Obtain Future" },
  { id: 1005, label: "Oddjob" },
  { id: 1374, label: "Office Takeout" },
  { id: 234, label: "Oh! Production" },
  { id: 28, label: "OLM" },
  { id: 1231, label: "OLM Digital" },
  { id: 313, label: "Omnibus Japan" },
  { id: 1717, label: "Onionskin" },
  { id: 1600, label: "On-Lead" },
  { id: 1013, label: "Opera House" },
  { id: 1109, label: "Orange" },
  { id: 334, label: "Ordet" },
  { id: 831, label: "Otogi Production" },
  { id: 1443, label: "Overlap" },
  { id: 455, label: "Palm Studio" },
  { id: 862, label: "Pashmina" },
  { id: 911, label: "Passione" },
  { id: 413, label: "Pastel" },
  { id: 132, label: "P.A. Works" },
  { id: 1425, label: "5pb." },
  { id: 329, label: "Phoenix Entertainment" },
  { id: 1751, label: "pH Studio" },
  { id: 78, label: "Picture Magic" },
  { id: 1229, label: "Pie in the sky" },
  { id: 1129, label: "Pierrot Plus" },
  { id: 1295, label: "Pine Jam" },
  { id: 45, label: "Pink Pineapple" },
  { id: 204, label: "Pioneer LDC" },
  { id: 195, label: "Pixy" },
  { id: 175, label: "Planet" },
  { id: 1471, label: "Platinum Vision" },
  { id: 107, label: "Plum" },
  { id: 1023, label: "Polygon Pictures" },
  { id: 1201, label: "Ponycan USA" },
  { id: 144, label: "Pony Canyon" },
  { id: 1557, label: "Pony Canyon Enterprise" },
  { id: 365, label: "PoRO" },
  { id: 753, label: "PRA" },
  { id: 347, label: "PrimeTime" },
  { id: 1185, label: "81 Produce" },
  { id: 10, label: "Production I.G" },
  { id: 1053, label: "Production IMS" },
  { id: 196, label: "Production Reed" },
  { id: 439, label: "Project No.9" },
  { id: 1065, label: "Public & Basic" },
  { id: 1287, label: "Q-Tec" },
  { id: 977, label: "Queen Bee" },
  { id: 1631, label: "Radio Osaka" },
  { id: 81, label: "Radix" },
  { id: 211, label: "Rakuonsha" },
  { id: 1581, label: "RAY" },
  { id: 1181, label: "RG Animation Studios" },
  { id: 253, label: "Rikuentai" },
  { id: 1067, label: "Rising Force" },
  { id: 249, label: "Robot Communications" },
  { id: 160, label: "Rondo Robe" },
  { id: 841, label: "Saban Entertainment" },
  { id: 1934, label: "Saigo no Shudan" },
  { id: 765, label: "Sakura Create" },
  { id: 1345, label: "Sammy" },
  { id: 150, label: "Sanrio" },
  { id: 537, label: "SANZIGEN" },
  { id: 41, label: "Satelight" },
  { id: 422, label: "Schoolzone" },
  { id: 1591, label: "Science SARU" },
  { id: 167, label: "Sega" },
  { id: 1836, label: "SELFISH" },
  { id: 376, label: "Sentai Filmworks" },
  { id: 541, label: "Seven" },
  { id: 35, label: "Seven Arcs" },
  { id: 1569, label: "Seven Arcs Pictures" },
  { id: 44, label: "Shaft" },
  { id: 471, label: "Shanghai Animation Film Studio" },
  { id: 1667, label: "Shanghai Foch Film Culture Investment" },
  { id: 1147, label: "Shinano Kikaku" },
  { id: 247, label: "Shin-Ei Animation" },
  { id: 192, label: "Shinkuukan" },
  { id: 235, label: "Shirogumi" },
  { id: 109, label: "Shochiku" },
  { id: 1430, label: "Shogakukan" },
  { id: 474, label: "Shogakukan Music & Digital Entertainment" },
  { id: 62, label: "Shogakukan Productions" },
  { id: 1737, label: "Shout! Factory" },
  { id: 777, label: "Showgate" },
  { id: 1365, label: "Shueisha" },
  { id: 1119, label: "Shuka" },
  { id: 1278, label: "Signal.MD" },
  { id: 300, label: "Silver Link." },
  { id: 147, label: "SKY Perfect Well Think" },
  { id: 149, label: "SME Visual Works" },
  { id: 1647, label: "Smiral Animation" },
  { id: 1372, label: "SOEISHINSHA" },
  { id: 621, label: "SoftBank Creative" },
  { id: 813, label: "SoftCel Pictures" },
  { id: 254, label: "Soft Garage" },
  { id: 153, label: "SoftX" },
  { id: 161, label: "Sogo Vision" },
  { id: 1189, label: "Sola Digital Arts" },
  { id: 1858, label: "Sonilude" },
  { id: 737, label: "Sony Music Communications" },
  { id: 757, label: "Sony Music Entertainment" },
  { id: 1516, label: "Sony PCL" },
  { id: 15, label: "Sony Pictures Entertainment" },
  { id: 64, label: "Sotsu" },
  { id: 1597, label: "Sotsu Music Publishing" },
  { id: 1294, label: "Sound Team Don Juan" },
  { id: 1045, label: "Space Neko" },
  { id: 1343, label: "Space Shower Music" },
  { id: 1768, label: "Sparkly Key Animation Studio" },
  { id: 58, label: "Square Enix" },
  { id: 92, label: "Starchild Records" },
  { id: 1197, label: "Steve N' Steven" },
  { id: 884, label: "Strawberry Meets Pictures" },
  { id: 1203, label: "Studio 1st" },
  { id: 1127, label: "Studio 3Hz" },
  { id: 13, label: "Studio 4°C" },
  { id: 407, label: "Studio 9 MAiami" },
  { id: 1209, label: "Studio A-CAT" },
  { id: 1252, label: "Studio Binzo" },
  { id: 478, label: "Studio Blanc" },
  { id: 1033, label: "Studio Colorido" },
  { id: 126, label: "Studio Comet" },
  { id: 37, label: "Studio Deen" },
  { id: 423, label: "Studio Eromatick" },
  { id: 24, label: "Studio Fantasia" },
  { id: 93, label: "Studio Flag" },
  { id: 36, label: "Studio Gallop" },
  { id: 21, label: "Studio Ghibli" },
  { id: 418, label: "Studio Gokumi" },
  { id: 101, label: "Studio Hibari" },
  { id: 829, label: "Studio Jack" },
  { id: 1375, label: "Studio Jam" },
  { id: 280, label: "Studio Junio" },
  { id: 937, label: "Studio Kaab" },
  { id: 909, label: "Studio Kelmadick" },
  { id: 256, label: "Studio Kikan" },
  { id: 177, label: "Studio Kyuuma" },
  { id: 1774, label: "Studio LAN" },
  { id: 1383, label: "Studio Live" },
  { id: 719, label: "Studio Mausu" },
  { id: 1155, label: "Studio Moriken" },
  { id: 199, label: "Studio Nue" },
  { id: 1, label: "Studio Pierrot" },
  { id: 443, label: "Studio PuYUKAI" },
  { id: 84, label: "Studio Rikka" },
  { id: 210, label: "Studio Tulip" },
  { id: 1244, label: "Studio VOLN" },
  { id: 1509, label: "Studio World" },
  { id: 435, label: "Studio Zero" },
  { id: 14, label: "Sunrise" },
  { id: 274, label: "Suzuki Mirano" },
  { id: 118, label: "SynergySP" },
  { id: 332, label: "Takeshobo" },
  { id: 103, label: "Tatsunoko Production" },
  { id: 145, label: "TBS" },
  { id: 1283, label: "TC Entertainment" },
  { id: 1499, label: "Techno Sound" },
  { id: 385, label: "Tele-Cartoon Japan" },
  { id: 94, label: "Telecom Animation Film" },
  { id: 358, label: "Telescreen" },
  { id: 1349, label: "Tencent Animation & Comics" },
  { id: 1727, label: "Tencent Penguin Pictures" },
  { id: 200, label: "Tezuka Productions" },
  { id: 229, label: "The Answer Studio" },
  { id: 1250, label: "The National Film Center Japan" },
  { id: 499, label: "The Pokemon Company International" },
  { id: 73, label: "TMS Entertainment" },
  { id: 120, label: "TNK" },
  { id: 18, label: "Toei Animation" },
  { id: 141, label: "Toei Video" },
  { id: 1015, label: "T.O Entertainment" },
  { id: 245, label: "Toho" },
  { id: 1143, label: "TOHO animation" },
  { id: 577, label: "Tohokushinsha Film Corporation" },
  { id: 905, label: "Tokuma Japan" },
  { id: 382, label: "Tokuma Shoten" },
  { id: 122, label: "Tokyo Kids" },
  { id: 65, label: "Tokyo Movie Shinsha" },
  { id: 1211, label: "Tokyo MX" },
  { id: 484, label: "Tokyopop" },
  { id: 1319, label: "Tokyo Theatres" },
  { id: 363, label: "Topcraft" },
  { id: 882, label: "Toranoana" },
  { id: 1685, label: "Toshiba Digital Frontiers" },
  { id: 224, label: "Toshiba EMI" },
  { id: 741, label: "Toshiba Entertainment" },
  { id: 1390, label: "Toy's Factory" },
  { id: 80, label: "Trans Arts" },
  { id: 405, label: "T-Rex" },
  { id: 110, label: "Triangle Staff" },
  { id: 803, label: "Trigger" },
  { id: 63, label: "Trinet Entertainment" },
  { id: 643, label: "Trinity Sound" },
  { id: 860, label: "Triple X" },
  { id: 1103, label: "TROYCA" },
  { id: 453, label: "Tsuburaya Productions" },
  { id: 390, label: "Tsuchida Productions" },
  { id: 55, label: "TV Asahi" },
  { id: 100, label: "TV Osaka" },
  { id: 16, label: "TV Tokyo" },
  { id: 717, label: "TV Tokyo Music" },
  { id: 1747, label: "Twin Engine" },
  { id: 1451, label: "TYO" },
  { id: 333, label: "TYO Animations" },
  { id: 1340, label: "Typhoon Graphics" },
  { id: 43, label: "ufotable" },
  { id: 539, label: "Ultra Super Pictures" },
  { id: 1447, label: "Urban Vision" },
  { id: 472, label: "Usagi Ou" },
  { id: 29, label: "VAP" },
  { id: 945, label: "Vasoon Animation" },
  { id: 136, label: "Vega Entertainment" },
  { id: 123, label: "Victor Entertainment" },
  { id: 1718, label: "Virgin Babylon Records" },
  { id: 246, label: "Visual 80" },
  { id: 203, label: "Visual Art's" },
  { id: 119, label: "Viz Media" },
  { id: 450, label: "Wako Productions" },
  { id: 417, label: "Walt Disney Studios" },
  { id: 318, label: "WAO World" },
  { id: 415, label: "Warner Bros. Japan" },
  { id: 1011, label: "Warner Music Japan" },
  { id: 1772, label: "Wawayu Animation" },
  { id: 314, label: "White Fox" },
  { id: 858, label: "Wit Studio" },
  { id: 33, label: "WOWOW" },
  { id: 1396, label: "W-Toon Studio" },
  { id: 27, label: "Xebec" },
  { id: 1572, label: "XFLAG" },
  { id: 795, label: "Yahoo! Japan" },
  { id: 1055, label: "Yamamura Animation, Inc." },
  { id: 1431, label: "Yaoqi" },
  { id: 1560, label: "Yaoyorozu" },
  { id: 127, label: "Yomiko Advertising" },
  { id: 675, label: "Yomiuri Advertising" },
  { id: 76, label: "Yomiuri Telecasting" },
  { id: 1492, label: "Yomiuri TV Enterprise" },
  { id: 239, label: "Y.O.U.C" },
  { id: 220, label: "Youmex" },
  { id: 236, label: "YTV" },
  { id: 96, label: "Yumeta Company" },
  { id: 1379, label: "Zero-G" },
  { id: 1131, label: "Zero-G Room" },
  { id: 218, label: "Zexcs" },
];
